version: '3.7'

services:
  debian:
    build: docker/debian
    networks:
      web:
      ansible:
        ipv4_address: 172.40.1.1
    tty: true
    volumes:
    - ./docker/storage:/home/exploit/docker
    - /home/exploit/docker/storage
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`ansible.localhost`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=80"
      - "traefik.http.routers.portainer.entrypoints=http"
    cap_add:
      - NET_ADMIN

networks:
  web:
    external: true
  ansible:
    ipam:
      driver: default
      config:
       - subnet: 172.40.0.0/16

