---
- hosts: dev

  vars_files:
#    - ./vault/develop.yml #Uncomment this to use the vault for not the default dev variables
    - ./vars/vars.yml #This gets overriden by the group_vars dev.yml file

  roles:
    - oh-my-zsh
    - ssh-banner #Will not display in dev as the system can not be resterted as it is not booted with systemd
    - docker
    - traefik
    - portainer
    - maria
    - test-docker
    - reboot #Skipped on dev